// ============================================================
// Cleanup Duplicate Menu Items — Gangaram
// Purges duplicate items generated by old non-idempotent script
//
// Usage:
//   npx tsx scripts/cleanup-duplicate-menu-items.ts
// ============================================================

import { initializeApp, cert, getApps } from "firebase-admin/app";
import { getFirestore } from "firebase-admin/firestore";
import * as fs from "fs";
import * as path from "path";

function normalizeEnvValue(value: string): string {
  const trimmed = value.trim();
  if (
    (trimmed.startsWith('"') && trimmed.endsWith('"')) ||
    (trimmed.startsWith("'") && trimmed.endsWith("'"))
  ) {
    return trimmed.slice(1, -1);
  }
  return trimmed;
}

const envPath = path.resolve(__dirname, "../.env.local");
if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, "utf-8");
  for (const line of envContent.split("\n")) {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith("#")) {
      const eqIndex = trimmed.indexOf("=");
      if (eqIndex > 0) {
        const key = trimmed.slice(0, eqIndex).trim();
        const value = normalizeEnvValue(trimmed.slice(eqIndex + 1));
        process.env[key] = value;
      }
    }
  }
}

async function cleanup() {
  if (!getApps().length) {
    const privateKey = normalizeEnvValue(process.env.FIREBASE_ADMIN_PRIVATE_KEY ?? "")
      .replace(/\\r\\n/g, "\n")
      .replace(/\\n/g, "\n");

    initializeApp({
      projectId: process.env.FIREBASE_ADMIN_PROJECT_ID,
      credential: cert({
        projectId: process.env.FIREBASE_ADMIN_PROJECT_ID!,
        clientEmail: process.env.FIREBASE_ADMIN_CLIENT_EMAIL!,
        privateKey,
      }),
    });
  }

  const db = getFirestore();
  const merchantId = "demo-merchant-1";
  
  console.log(`🧹 Scanning menus for ${merchantId}...`);

  const menuCol = db.collection(`merchants/${merchantId}/menus`);
  const snapshot = await menuCol.get();
  
  const totalScanned = snapshot.size;
  let duplicatesRemoved = 0;
  
  // Track documents by item name
  // name -> array of {id, createdAt (or id length proxy if no createdAt exists)}
  const nameMap = new Map<string, {id: string, ref: any}[]>();

  snapshot.forEach(doc => {
    const data = doc.data();
    const name = data.name;
    if (!name) return;
    
    if (!nameMap.has(name)) {
      nameMap.set(name, []);
    }
    nameMap.get(name)!.push({ id: doc.id, ref: doc.ref });
  });

  const batch = db.batch();

  for (const [name, docs] of nameMap.entries()) {
    if (docs.length > 1) {
      // Keep the document with the slugified ID if it exists, otherwise keep the first one
      const slugId = name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
      const slugDoc = docs.find(d => d.id === slugId);
      
      const keeperId = slugDoc ? slugDoc.id : docs[0].id;
      
      for (const d of docs) {
        if (d.id !== keeperId) {
          console.log(`🗑️ Deleting duplicate: ${name} (ID: ${d.id})`);
          batch.delete(d.ref);
          duplicatesRemoved++;
        }
      }
    }
  }

  if (duplicatesRemoved > 0) {
    await batch.commit();
  }

  console.log(`\n✅ Cleanup Summary:`);
  console.log(`   Total items scanned: ${totalScanned}`);
  console.log(`   Duplicates removed: ${duplicatesRemoved}`);
  console.log(`   Remaining items: ${totalScanned - duplicatesRemoved}`);
  
  process.exit(0);
}

cleanup().catch((err) => {
  console.error("❌ Cleanup failed:", err);
  process.exit(1);
});
